token: # discord token
guild: # guild id
boarding: # boarding channel id
image: # bot logo
campuses: # list of campuses
  - foo # primary campus (default campus when option isn't provided)
  - bar
seasons: # list of seasons
  - baz # primary season (default season when option isn't provided)
  - qux
season_data: # season data
  baz:
    name: baz
    term: 1
    year: 2000
  qux:
    name: qux
    term: 2
    year: 3000
